apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphite-pvc
  namespace: test-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
